# Generated by Django 4.2.7 on 2024-07-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='img',
            field=models.ImageField(default='default_image.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
