# Generated by Django 4.2.7 on 2024-07-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_pizzamodel_img_alter_customermodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phoneno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='userid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='ordereditems',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phoneno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
