# Generated by Django 4.2.7 on 2024-07-30 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizzaapp', '0006_alter_customermodel_phoneno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
