# Generated by Django 4.2.7 on 2024-07-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0007_alter_customermodel_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='userid',
            field=models.CharField(max_length=255),
        ),
    ]
